version: "3"
networks:
  nocobase:
    driver: bridge
services:
  app:
    image: nocobase/nocobase:0.7.7-alpha.1
    networks:
      - nocobase
    environment:
      - APP_ENV=production
      - LOCAL_STORAGE_BASE_URL=/storage/uploads
    volumes:
      - ./storage:/app/nocobase/storage
    ports:
      - "13000:80"